### ISSUE TITLE
配置怎么使用 

### ISSUE THREAD

**Issue by nyb112** [Web3123/v2ray#2]
有详细的使用教程么。 demo连不上网络

**Comment by Web3123** [comment]
> 有详细的使用教程么。 demo连不上网络

留下你的联系方式吧

**Comment by Web3123** [comment]
> > 有详细的使用教程么。 demo连不上网络
> 
> 留下你的联系方式吧

最好是留下你的telegram

**Comment by Web3123** [comment]
https://t.me/v2ray_1234

**Comment by Web3123** [comment]
不提问我就关了
